import { test, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const shots = 'artifacts/screenshots';
test.beforeEach(async ({ page }) => {
  await mkdir(shots, { recursive: true });
  await page.goto('/');
  await page.getByRole('button', { name: 'Load demo', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'What matters to you?' })).toBeVisible();
  await expect(page.locator('[data-nextjs-dialog]')).toHaveCount(0);
});
async function analyze(page: import('@playwright/test').Page, path: string) {
  await page.getByRole('button', { name: 'Demo controls' }).click();
  await page.getByLabel('Try a path').selectOption(path);
  await page.getByRole('button', { name: 'Interpret my needs' }).click();
  await expect(page.getByRole('heading', { name: 'Your buying criteria' })).toBeVisible();
  await page.getByRole('button', { name: 'Confirm & analyze reviews' }).click();
  await expect(page.getByRole('heading', { name: 'Evidence, in your context.' })).toBeVisible();
}
test('A: comfort conflict → investigate → brief → source review; reload restores', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.screenshot({ path: `${shots}/criteria.png`, fullPage: true });
  await analyze(page, 'conflict');
  await expect(page.getByRole('button', { name: 'Read decision brief' })).toBeVisible();
  await expect(page.getByText('Context difference found')).toBeVisible();
  await page.screenshot({ path: `${shots}/workspace.png`, fullPage: true });
  await page.getByRole('button', { name: 'Read decision brief' }).click();
  await expect(page.getByRole('heading', { name: 'Before you buy' })).toBeVisible();
  await page.screenshot({ path: `${shots}/brief.png`, fullPage: true });
  await page.getByRole('button', { name: 'R5' }).first().click();
  await expect(page.getByRole('dialog')).toContainText('Wearing glasses');
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.reload(); await page.getByRole('button', { name: '3 Decision brief' }).click();
  await expect(page.getByText('Complete with caveats', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
test('B: office-only ANC → request → skip → insufficient brief', async ({ page }) => {
  await analyze(page, 'missing');
  await expect(page.getByRole('heading', { name: 'Can you add relevant evidence?' })).toBeVisible();
  await page.screenshot({ path: `${shots}/missing-evidence.png`, fullPage: true });
  await page.getByRole('button', { name: 'Skip & keep unknown' }).click();
  await page.getByRole('button', { name: 'Read decision brief' }).click();
  await expect(page.getByText('Critical evidence missing', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Unknowns' })).toBeVisible();
  await page.screenshot({ path: `${shots}/stopped-brief.png`, fullPage: true });
});
test('C: add subway evidence → reanalyze → complete brief', async ({ page }) => {
  await analyze(page, 'missing');
  await page.getByRole('button', { name: 'Load synthetic subway reviews' }).click();
  await page.getByRole('button', { name: 'Add & reanalyze' }).click();
  await page.getByRole('button', { name: 'Read decision brief' }).click();
  await expect(page.getByText('Complete with caveats', { exact: true })).toBeVisible();
  await expect(page.getByText(/6 reviews · \d+ cited items/)).toBeVisible();
  await expect(page.getByText('On the subway, after two weeks of commuting', { exact: false }).first()).toBeVisible();
});
test('explicit mobile demo criteria, workspace and brief fit viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Interpret my needs' }).click();
  await expect(page.getByRole('heading', { name: 'Your buying criteria' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: `${shots}/mobile-criteria.png`, fullPage: true });
  await page.getByRole('button', { name: 'Confirm & analyze reviews' }).click();
  await expect(page.getByRole('button', { name: 'Read decision brief' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: `${shots}/mobile-workspace.png`, fullPage: true });
  await page.getByRole('button', { name: 'Read decision brief' }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: `${shots}/mobile-brief.png`, fullPage: true });
});
test('disabled live flag leaves the explicit demo usable and blocks live API calls', async ({ page, request }) => {
  const config = await (await request.get('/api/config')).json();
  test.skip(config.live || config.persistence, 'Live-flag-disabled checks only.');
  await page.getByRole('button', { name: 'Demo controls' }).click();
  await expect(page.getByText('Deterministic demo', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Start live analysis' })).toHaveCount(0);
  const restore = await request.get('/api/session');
  expect((await restore.json()).session).toBeNull();
  const create = await request.post('/api/session', { headers: { Origin: new URL(page.url()).origin }, data: { action: 'create', mode: 'live', product: 'Demo-H1', need: 'Library and subway', reviewText: 'A review' } });
  expect(create.status()).toBe(403); expect((await create.json()).error).toContain('disabled');
  const crossOrigin = await request.post('/api/session', { headers: { Origin: 'https://example.org' }, data: { action: 'step' } });
  expect(crossOrigin.status()).toBe(403);
});
test('selected action and rationale are visible; collapsed activity retains records; criteria edit starts fresh', async ({ page }) => {
  await analyze(page, 'missing');
  const panel = page.locator('.agent-panel');
  await expect(panel.getByRole('heading', { name: 'Agent chose: Request evidence' })).toBeVisible();
  await expect(panel).toContainText('Reason: Office ANC cannot answer your subway question.');
  await expect(panel).toContainText('Decision 1 of 5');
  const activity = page.locator('details.activity');
  await expect(activity).not.toHaveAttribute('open');
  await page.getByText('Agent activity', { exact: true }).click();
  await expect(activity).toHaveAttribute('open', '');
  await expect(activity.locator('li').filter({ hasText: 'extract evidence' })).toHaveCount(2);
  await expect(activity.locator('li').filter({ hasText: 'request evidence' })).toHaveCount(1);
  await page.getByText('Agent activity', { exact: true }).click();
  await page.screenshot({ path: `${shots}/agent-decision-focused.png`, fullPage: true });
  await page.getByRole('button', { name: 'Edit criteria', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your buying criteria' })).toBeVisible();
  await page.getByLabel('Study session minutes').fill('180');
  await page.getByRole('button', { name: 'Confirm & analyze reviews' }).click();
  await expect(page.getByRole('heading', { name: 'Can you add relevant evidence?' })).toBeVisible();
  await expect(panel).toContainText('Decision 1 of 5');
  const state = await page.evaluate(() => JSON.parse(localStorage.getItem('buylens-demo-v1')!));
  expect(state.version).toBe(2);
  expect(state.requests).toBe(1);
  expect(state.iterations).toBe(1);
  expect(state.brief).toBeNull();
});
test('Agent Run, evidence details, Markdown and measured evaluation render without changing three screens', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await analyze(page, 'conflict');
  await expect(page.getByRole('button', { name: 'Read decision brief' })).toBeVisible();
  const run = page.locator('details.agent-run');
  await expect(run).not.toHaveAttribute('open');
  await run.getByText('Agent Run', { exact: true }).click();
  await expect(run).toContainText('Investigate conflict');
  await expect(run).toContainText('Controller validation');
  await expect(run).toContainText('COMPLETED');
  await expect(run).toContainText('ms');
  await expect(run.locator('.run-metrics')).toContainText('Model call count0');
  await expect(page.locator('details.activity')).not.toHaveAttribute('open');
  await page.screenshot({ path: `${shots}/portfolio-agent-run.png`, fullPage: true });
  await page.getByRole('button', { name: 'R5' }).first().click();
  const dialog = page.getByRole('dialog');
  for (const label of ['Original review', 'Exact quote', 'Criterion', 'Direction / relevance', 'Evidence quality', 'Detected usage context', 'Wearing duration', 'Rating / text contradiction', 'Why this matters', 'Citation verified']) await expect(dialog).toContainText(label);
  const state = await page.evaluate(() => JSON.parse(localStorage.getItem('buylens-demo-v1')!));
  const quote = await dialog.locator('.exact-quote').innerText();
  expect(state.reviews.find((r: {id: string}) => r.id === 'R5').rawText).toContain(quote);
  await page.screenshot({ path: `${shots}/portfolio-evidence-details.png` });
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Read decision brief' }).click();
  await page.getByRole('button', { name: 'View Markdown Brief' }).click();
  const markdown = page.getByLabel('Markdown brief', { exact: true });
  await expect(markdown).toContainText('# BuyLens Purchase Decision Brief');
  await expect(markdown).toContainText('## Evidence Gaps / Unknowns');
  await expect(markdown).toContainText('[R5](#source-r5)');
  const after = await page.evaluate(() => JSON.parse(localStorage.getItem('buylens-demo-v1')!));
  expect(after.run).toEqual(state.run);
  await page.screenshot({ path: `${shots}/portfolio-markdown.png`, fullPage: true });
  await page.reload(); await page.getByRole('button', { name: '2 Evidence workspace' }).click();
  await page.locator('details.agent-run summary').click();
  await expect(page.locator('details.agent-run')).toContainText('Investigate conflict');
  await page.getByRole('link', { name: 'Portfolio evaluation' }).click();
  await expect(page.getByRole('heading', { name: 'Portfolio evaluation' })).toBeVisible();
  await expect(page.getByText('8 scenarios tested.', { exact: true })).toBeVisible();
  await expect(page.locator('tbody tr')).toHaveCount(8);
  await expect(page.locator('tbody')).not.toContainText('FAIL');
  await expect(page.getByText(/LIVE VERIFIED 2026-10-06 — 3\/3 synthetic live scenarios passed/)).toBeVisible();
  await page.screenshot({ path: `${shots}/portfolio-evaluation.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});
