import { test, expect, type BrowserContext, type Page } from '@playwright/test';
import type { Session } from '../../src/lib/types';

const cases = [
  { name: 'carry-on suitcase', product: '', need: 'I travel several times a year and take trains to the airport. I need a carry-on under $200 that is light and durable.', category: /suitcase|luggage|carry.on/i, features: [/carry.on|cabin/i, /light|weight|portab/i, /durab/i], budget: 200, excluded: /office chair|lumbar|air fryer/i },
  { name: 'office chair', product: 'Office chair', need: 'I work at my desk 8 hours a day. My lower back gets tired. I care about lumbar support and adjustability and want to stay under $350.', category: /chair/i, features: [/lumbar|lower.back/i, /adjust/i], budget: 350, excluded: /suitcase|luggage|carry.on|air fryer/i },
  { name: 'air fryer', product: 'Air fryer', need: 'I cook for one person in a small apartment. Easy cleaning and small footprint matter more than maximum capacity.', category: /air fryer/i, features: [/clean/i, /footprint|compact|space|size/i], budget: null, excluded: /suitcase|luggage|carry.on|office chair|lumbar/i },
];
const headphoneLeak = /headphones?|Demo-H1|\bANC\b|subway/i;

test.describe.serial('Unseen real purchase needs — UI → live model → confirmed state → missing evidence', () => {
  test.setTimeout(180000);
  let context: BrowserContext;
  let page: Page;
  let previousId: string | null = null;
  test.beforeAll(async ({ browser }) => {
    context = await browser.newContext();
    page = await context.newPage();
    const config = await (await page.request.get('/api/config')).json();
    expect(config.live, 'Real model configuration is required; do not replace this test with fixtures.').toBe(true);
    expect(config.persistence).toBe(true);
    // Simulate the old demo residue that must no longer initialize a purchase.
    await page.addInitScript(() => localStorage.setItem('buylens-demo-v1', JSON.stringify({ mode: 'demo', product: 'Demo-H1 headphones', need: 'subway ANC', reviewText: 'old headphone review', criteria: [], log: [] })));
  });
  test.afterAll(async () => { await context?.close(); });

  for (const scenario of cases) test(scenario.name, async () => {
    if (previousId) await page.getByRole('button', { name: 'New purchase', exact: true }).click();
    else await page.goto('/');
    await expect(page.getByRole('heading', { name: 'What matters to you?' })).toBeVisible();
    await expect(page.locator('#need')).toHaveValue('');
    await expect(page.locator('#product')).toHaveValue('');
    await expect(page.locator('#reviews')).toHaveValue('');
    expect(await page.locator('body').innerText()).not.toMatch(headphoneLeak);
    if (scenario.product) await page.locator('#product').fill(scenario.product);
    await page.locator('#need').fill(scenario.need);
    const modelResponse = page.waitForResponse(response => response.url().endsWith('/api/session') && response.request().method() === 'POST' && response.request().postDataJSON()?.action === 'interpret');
    await page.getByRole('button', { name: 'Interpret my needs' }).click();
    let response = await modelResponse;
    let body = await response.json();
    expect(response.ok(), body.error).toBe(true);
    let parsed = body.session as Session;
    if (parsed.phase === 'clarify') {
      expect(parsed.question?.trim()).toBeTruthy();
      await page.getByLabel('Clarification answer').fill('Use the product and priorities already stated. Keep any unstated dimensions or numerical limits unknown; do not assume them.');
      const clarified = page.waitForResponse(r => r.url().endsWith('/api/session') && r.request().postDataJSON()?.action === 'clarify');
      await page.getByRole('button', { name: 'Update criteria', exact: true }).click();
      response = await clarified; body = await response.json(); expect(response.ok(), body.error).toBe(true); parsed = body.session;
    }
    expect(parsed.need).toContain(scenario.need);
    expect(parsed.product).toMatch(scenario.category);
    expect(parsed.criteria.length).toBeGreaterThanOrEqual(2);
    for (const feature of scenario.features) expect(JSON.stringify(parsed.criteria)).toMatch(feature);
    if (scenario.budget !== null) expect(parsed.criteria.some(c => c.priority === 'Hard constraint' && c.constraint?.operator === 'lte' && c.constraint.value === scenario.budget && c.constraint.unit === 'USD')).toBe(true);
    else expect(parsed.criteria.every(c => c.constraint === null)).toBe(true);
    expect(parsed.run?.some(r => r.name === 'Understand criteria' && r.type === 'MODEL' && r.status === 'COMPLETED')).toBe(true);
    expect(JSON.stringify(parsed)).not.toMatch(headphoneLeak);
    expect(JSON.stringify(parsed)).not.toMatch(scenario.excluded);
    await expect(page.getByText('Generated by AI from your need. Confirm or edit.', { exact: true })).toBeVisible();
    const criteria = structuredClone(parsed.criteria);
    const confirmedResponse = page.waitForResponse(r => r.url().endsWith('/api/session') && r.request().postDataJSON()?.action === 'confirm');
    await page.getByRole('button', { name: 'Confirm & analyze reviews' }).click();
    const confirmed = (await (await confirmedResponse).json()).session as Session;
    expect(confirmed.confirmed).toBe(true); expect(confirmed.criteria).toEqual(criteria);
    await expect(page.getByRole('heading', { name: 'Can you add relevant evidence?' })).toBeVisible({ timeout: 90000 });
    const stored = (await (await page.request.get('/api/session')).json()).session as Session;
    expect(stored.mode).toBe('live'); expect(stored.phase).toBe('waiting');
    expect(stored.product).toBe(parsed.product); expect(stored.criteria).toEqual(criteria);
    expect(stored.reviewText).toBe(''); expect(stored.reviews).toEqual([]); expect(stored.evidence).toEqual([]); expect(stored.conflicts).toEqual([]);
    expect(stored.brief).toBeNull(); expect(stored.decision?.action).toBe('REQUEST_EVIDENCE'); expect(stored.requests).toBe(1);
    expect(stored.modelCall?.function.name).toBe('REQUEST_EVIDENCE');
    expect(stored.assessments.every(a => a.units === 0 && a.coverage === 'insufficient')).toBe(true);
    expect(stored.run?.some(r => r.name === 'No supplied review evidence' && r.type === 'CONTROLLER')).toBe(true);
    expect(stored.run?.some(r => r.type === 'MODEL' && r.name.includes('Extract'))).toBe(false);
    expect(JSON.stringify(stored)).not.toMatch(headphoneLeak);
    expect(JSON.stringify(stored)).not.toMatch(scenario.excluded);
    if (previousId) expect(stored.id).not.toBe(previousId);
    previousId = stored.id;
    await page.screenshot({ path: `artifacts/screenshots/generic-${scenario.name.replaceAll(' ', '-')}.png`, fullPage: true });
    await page.reload();
    await page.getByRole('button', { name: '2 Evidence workspace' }).click();
    await expect(page.getByRole('heading', { name: 'Can you add relevant evidence?' })).toBeVisible();
    const restored = (await (await page.request.get('/api/session')).json()).session as Session;
    expect(restored.criteria).toEqual(criteria); expect(restored.need).toBe(stored.need);
    expect(await page.locator('body').innerText()).not.toMatch(headphoneLeak);
    if (scenario.name === 'carry-on suitcase') {
      // Newly authored synthetic validation reviews, never demo-fixture fallback.
      const reviews = 'I paid $179 for this carry-on suitcase and have used it on eight flights in six months. It weighs 2.7 kg empty. It fit the cabin sizing frame on my flights, was easy to carry on trains to the airport, and the wheels and handle remain intact.' + '\n\n' + 'My carry-on suitcase cost $189. After ten trips over nine months, its shell and wheels still work well. Empty weight is 2.6 kg, so lifting it on airport trains is manageable. It fitted the overhead cabin space on my flights; I still check each airline size rule.';
      await page.getByLabel('Additional reviews').fill(reviews);
      await page.getByRole('button', { name: 'Add & reanalyze' }).click();
      await expect(page.getByRole('button', { name: 'Read decision brief' })).toBeVisible({ timeout: 120000 });
      const analyzed = (await (await page.request.get('/api/session')).json()).session as Session;
      expect(analyzed.version).toBe(stored.version + 1); expect(analyzed.requests).toBe(stored.requests);
      expect(analyzed.log.slice(0, stored.log.length)).toEqual(stored.log);
      expect(analyzed.criteria).toEqual(criteria); expect(analyzed.reviews.length).toBe(2);
      expect(analyzed.evidence.length).toBeGreaterThan(0);
      for (const evidence of analyzed.evidence) {
        expect(criteria.some(c => c.id === evidence.criterionId)).toBe(true);
        expect(analyzed.reviews.find(r => r.id === evidence.reviewId)?.rawText).toContain(evidence.quote);
      }
      expect(analyzed.run?.some(r => r.type === 'MODEL' && r.name === 'Extract structured evidence' && r.status === 'COMPLETED')).toBe(true);
      expect(JSON.stringify(analyzed)).not.toMatch(headphoneLeak);
      await page.getByRole('button', { name: 'Read decision brief' }).click();
      expect(await page.locator('body').innerText()).not.toMatch(headphoneLeak);
    } else if (scenario.name === 'air fryer') {
      await page.getByRole('button', { name: 'Skip & keep unknown' }).click();
      await expect(page.getByRole('button', { name: 'Read decision brief' })).toBeVisible({ timeout: 90000 });
      const stopped = (await (await page.request.get('/api/session')).json()).session as Session;
      expect(stopped.decision?.action).toBe('STOP_INSUFFICIENT'); expect(stopped.brief?.incomplete).toBe(true);
      expect(stopped.brief?.fits).toEqual([]); expect(stopped.brief?.risks).toEqual([]);
      expect(JSON.stringify(stopped)).not.toMatch(headphoneLeak); expect(JSON.stringify(stopped)).not.toMatch(scenario.excluded);
      await page.getByRole('button', { name: 'Read decision brief' }).click();
      expect(await page.locator('body').innerText()).not.toMatch(headphoneLeak);
    }
  });

  test('vague natural-language need asks once, then infers the clarified product without default constraints', async () => {
    if (previousId) await page.getByRole('button', { name: 'New purchase', exact: true }).click();
    else await page.goto('/');
    const raw = 'I want to buy something good for my home, but I have not decided what I need yet.';
    await page.locator('#need').fill(raw);
    const first = page.waitForResponse(r => r.url().endsWith('/api/session') && r.request().postDataJSON()?.action === 'interpret');
    await page.getByRole('button', { name: 'Interpret my needs' }).click();
    let response = await first; let body = await response.json(); expect(response.ok(), body.error).toBe(true);
    const vague = body.session as Session;
    expect(vague.need).toBe(raw); expect(vague.phase).toBe('clarify'); expect(vague.question?.trim()).toBeTruthy();
    expect(vague.productProvided).toBe(false);
    expect(vague.criteria.every(c => c.constraint === null && c.minutes === null)).toBe(true);
    await page.getByLabel('Clarification answer').fill('I am looking for an air fryer for one person. Easy cleaning and small footprint are my priorities. I have no budget limit to specify yet.');
    const second = page.waitForResponse(r => r.url().endsWith('/api/session') && r.request().postDataJSON()?.action === 'clarify');
    await page.getByRole('button', { name: 'Update criteria', exact: true }).click();
    response = await second; body = await response.json(); expect(response.ok(), body.error).toBe(true);
    const clarified = body.session as Session;
    expect(clarified.product).toMatch(/air fryer/i); expect(clarified.clarifications).toBe(1); expect(clarified.question).toBeNull();
    expect(clarified.criteria.every(c => c.constraint === null && c.minutes === null)).toBe(true);
    expect(clarified.run?.filter(r => r.name === 'Understand criteria' && r.type === 'MODEL' && r.status === 'COMPLETED').length).toBe(2);
    expect(JSON.stringify(clarified)).not.toMatch(headphoneLeak);
    await page.getByRole('button', { name: 'Confirm & analyze reviews' }).click();
    await expect(page.getByRole('heading', { name: 'Can you add relevant evidence?' })).toBeVisible({ timeout: 90000 });
    const saved = (await (await page.request.get('/api/session')).json()).session as Session;
    expect(saved.criteria).toEqual(clarified.criteria); expect(saved.evidence).toEqual([]); expect(saved.reviews).toEqual([]);
  });
});
